### ISSUE TITLE
[App Request] - App to get Public Persona of Customer Live

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#126]
**Describe the sample app use-case :**
FullContact's [Enrich API](https://dashboard.fullcontact.com/api-ref#person-enrichment) offers a lot of public profile details at Person level. This can help agent customize the conversation based on customers interests at Person level and not at Company level.

**Features to Demonstrate**
This app should demonstrate 3 Advanced Features of the Platform
- **Request method** to reach FullContact's above mentioned endpoint and get the needed payload.
-  **Data Storage**  to store last 5 lookups performed and delete remaining.
-  **Instance Method** to get the required details to make a call from `conversation_user_info` placeholder and display the Person details in a Modal.

**More details :**
This endpoint requires email, twitter_id and FullName to send you required details about the person.

**Comment by sarfaraz187** [comment]
Hello saif,
I would like to contribute in building this app. If have any plan in mind for the app can you direct me towards it?

**Comment by Saif-Shines** [comment]
Hi @sarfaraz187 ,

This issue was created initially not for Hacktoberfest purpose, so this might require lot of time and effort. So you may choose to implement the aspects those will fit your time an expertise.

Having said that I will include it for hacktoberfest and let you know some of my thoughts that can help you as you plan to take it on.

1. App can use the [placeholder in Inbox Page](https://developers.freshchat.com/v2/docs/placeholders/#inbox_page).
2. Use [crayons](https://crayons.freshworks.com/components/) to quickly build up a small form that takes in email, twitter_id and Fullname.
3. Use [Request Method](https://developers.freshchat.com/v2/docs/request-method/) to make an request and store last 5 responses in [Data Store](https://developers.freshchat.com/v2/docs/data-storage/).
4.  This data got in response can be passed on to [an Modal](https://developers.freshchat.com/v2/docs/interface-method/#showmodal) via [Instance Method](https://developers.freshchat.com/v2/docs/instance-method/).

When this issue was created, Enrich API was free for developers to use to grab little details. I will let you choose any API that can be helpful that is free. The Goal is to demonstrate the features for others in the community to refer to. So having the part of just using Request Method is good enough without having to build complete app.

**Comment by sarfaraz187** [comment]
Hello @Saif-Shines , 

Thanks for your suggestions and assigning me this App. Yes Saif i will keep in mind the time and effort required. As you have suggested will work on one module at a time.
Regarding the Enrich API,
- Had gone through the documentation and was planning to use [Multi Field Request](https://dashboard.fullcontact.com/api-ref#multi-field-request) API.
- Enrich requires an API key in order to fetch data. Shall i setup an Iparams page to get the Enrich API key from the user. Let me know you thoughts on this?

**Comment by Saif-Shines** [comment]
That works @sarfaraz187 , anything as per your convenience.

**Comment by sarfaraz187** [comment]
Hello @Saif-Shines, 

Started working on Freshchat App Request and have implemented some of the features that had been requested. Kindly review the application and let me know your feedback [Git Repo](https://github.com/sarfaraz187/FullContact-Freshchat-App).

Here are few questions in which your suggestions can be helpful.

1. Contact information displayed in modal is it sufficient?
2. Since i am not any sending data back from modal to parent i haven't used instance API.
3. Is it fine to display the last 5 lookups in app itself or should i display in modal?

**Comment by Saif-Shines** [comment]
Hi @sarfaraz187 ,

We went through the code. Although there is a room for improvement, none of it is a blocker to have your code on this repository. If there is nothing else you'd add or subtract, please rase a PR adding [app's code to Demo Apps folder](https://github.com/freshworks/marketplace-sample-apps/tree/master/Demo-Apps).

Really appreciate your efforts and taking time to contribute.

**Comment by sarfaraz187** [comment]
Hi @Saif-Shines,

Thanks for the update. If you have any suggestions for improvement do let me know or else if you had in mind for others in our community to contribute in the improvement of this app i'll be more than happy to raise PR request with the current version.

**Comment by Saif-Shines** [comment]
Hey @sarfaraz187,

Raise a PR and let's have it merged. Then we will focus on improvements gradually. 😄
